"""Renamed OfferImage mimetype -> ext

Revision ID: a422fa4cf362
Revises: 6b0481379dda
Create Date: 2021-11-29 11:55:27.691384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a422fa4cf362'
down_revision = '6b0481379dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_images', sa.Column('ext', sa.String(length=6), nullable=False))
    op.drop_column('offer_images', 'mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_images', sa.Column('mimetype', sa.VARCHAR(length=6), nullable=False))
    op.drop_column('offer_images', 'ext')
    # ### end Alembic commands ###
