"""Added Location field into DB

Revision ID: b811c6f472a4
Revises: a422fa4cf362
Create Date: 2021-12-02 10:55:31.092656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b811c6f472a4'
down_revision = 'a422fa4cf362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'location')
    # ### end Alembic commands ###
